In [ ]:
class ParallemMachine:
    def __init__(self) -> None:
        pass

In [ ]:
# Generate test Case
import numpy as np
rng = np.random.default_rng()
m = 4
n = 100
w = list(rng.choice(91, n) + 10)
p = list(rng.choice(91, n) + 10)
print(m)
print(n)
print(w)
print(p)

In [13]:
import numpy as np

a = np.array([
    [0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
    [1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0],
    [0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
    [1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0],
    [1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1],
    [0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0],
    [0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1],
    [1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0]
])


p = np.array([1,2,3,5,7,8,9,10])
w = np.array([2,4,6,8,10,12,14,16])
temp = np.where(a[:, 0])[0]

def smith_order(s, p, w):
    rate = w[s] / p[s]
    order = rate.argsort()[::-1]             # get indexes of rate into decreasing order
    print(f"order { order}")
    return s[order]

print(smith_order(temp, p, w))
asub = p[temp]
print(asub)
print(np.cumsum(asub) @ w[temp])



order [0 3 1 2]
[1 7 3 4]
[ 2  5  7 10]
588


In [5]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
cumulative_sum_axis0 = np.cumsum(arr_2d, axis=0)  # Cumulative sum along columns
cumulative_sum_axis1 = np.cumsum(arr_2d, axis=1)  # Cumulative sum along rows

print("Cumulative Sum along Columns:\n", cumulative_sum_axis0)
print("Cumulative Sum along Rows:\n", cumulative_sum_axis1)

Cumulative Sum along Columns:
 [[ 1  2]
 [ 4  6]
 [ 9 12]]
Cumulative Sum along Rows:
 [[ 1  3]
 [ 3  7]
 [ 5 11]]



Miller-Tucker-Zemlin's model:
Optimal value: 330.0
x(1,4) = 1.0
x(2,3) = 1.0
x(3,5) = 1.0
x(4,2) = 1.0
x(5,1) = 1.0
u(5) = 4.0
u(2) = 2.0
u(3) = 3.0
u(4) = 1.0
[1, 4, 2, 3, 5]
[1, 4, 2, 3]


In [ ]:
# Contents Update